#!/bin/bash

supportedGames=("sampserver")
exists=0

read -r -p $'Please enter the game which you want to install: ' gameName

for i in ${supportedGames[@]}; do
  if [ $exists = 0 ] && [ "$i" = "$gameName" ]; then
    exists=1
    break
  fi
done

if [ $exists = 1 ]; then
  
  wget -q https://raw.githubusercontent.com/GameServerManagement/laucher/main/installers/$gameName installScript
  dos2unix -q installScript
  bash installScript
  sudo rm -rf installScript
  
else
  echo "The game is invalid."
fi
