#!/bin/bash

locationGSM=/usr/GSM
locationServer=/usr/GSM/sampserver
userLocationServer=/home/$(whoami)/GSM/sampserver
if [ "$(whoami)" = "root" ]; then
  userLocationServer=/root/GSM/sampserver
fi
serverNumber=0
created=0

for (( i=0; i<=100000000; i++ ))
do
  if [ ! -d "$locationServer-$i" ]; then
    sudo mkdir -p "$locationServer-$i"
    locationServer="$locationServer-$i"
    userLocationServer="$userLocationServer-$i"
    created=1
    serverNumber=$i
    break
  fi
done

if [ $created = 1 ]; then
  echo \-e "\033[0;32mSuccess: \033[0mCreated configuration files for sampserver-$serverNumber.\033[0m"
  echo ""
  echo \-e "\033[0;32mInfo: \033[0mThe server installation process has started. Please wait some minutes.\033[0m"
  echo ""
  # Setting up Server Files with random RCON Password
  mkdir -p $userLocationServer
  cd $userLocationServer
  wget -q https://github.com/GameServerManagement/laucher/raw/main/cdn/sampserver.tar.gz
  tar xzf sampserver.tar.gz && rm -f sampserver.tar.gz
  cd samp03 && mv * .. && cd ..
  rm -r samp03
  randomRconPassword=$( tr -dc A-Za-z0-9 </dev/urandom | head -c 16; echo '' )
  sudo rm -f LICENSE README
  sed -i -e "s/changeme/$randomRconPassword/g" server.cfg
  echo \-e "\033[0;32mSuccess: \033[0mServer files has been created for sampserver-$serverNumber. Waiting for installation of required libraries...\033[0m"
  echo ""
  # Setting up Libraries with libstdc++
  sudo apt-get install libstdc++6 -y >/dev/null
  sudo dpkg --add-architecture i386 >/dev/null
  sudo apt-get update -y >/dev/null
  sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 -y >/dev/null
  cd $userLocationServer/../..
  
  sudo cat >> "sampserver-$serverNumber" <<EOF
  sudo curl --silent "https://raw.githubusercontent.com/GameServerManagement/laucher/main/apps/sampserver?callingTime=$(date +%s)" >> sampserver-app
  sudo chmod +x sampserver-app
  sudo dos2unix -q sampserver-app
  sudo bash sampserver-app $1 $2 $3
  sudo rm -rf sampserver-app
EOF
  chmod +x sampserver-$serverNumber

  # Setting up Messages for installation and Updating config file from /usr/GSM
  sudo cat >> "/usr/GSM/sampserver-$serverNumber/config.gsm" <<EOM

installationPath=$userLocationServer
serverID=$serverNumber

EOM

  echo \-e "\033[0;32mSuccess: \033[0mThe server sampserver-$serverNumber has been succesfully installed.\033[0m"
  echo ""
  echo \-e "\033[0;32mInfo: \033[0mThe RCON password is \033[0;32m$randomRconPassword\033[0m. You can change it from \033[0;32m$userLocationServer/server.cfg\033[0m."
  echo ""
  echo \-e "\033[0;32mInfo: \033[0mTo start the server, use \033[0;32m./sampserver-$serverNumber start\033[0m."
  echo ""
else
  echo \-e "\033[0;31mError:\033[0m Couldn't create the folder for sampserver-$serverNumber. Please check permissions before reinstalling.\033[0m"
fi
